#!/bin/bash

user_interrupt(){
        echo -e "\n\nKeyboard Interrupt detected."
        echo -e "Cleaning Up and terminating..."
	sudo rm -rf src/
	exit
}

trap user_interrupt SIGINT
trap user_interrupt SIGTSTP

install(){
    # install requirements from pip
    sudo pip install -r requirements.txt --use-mirrors
    # install from package manager
    echo "What's your package manager?"
    echo "1. APT"
    echo "2. YUM"
    read opt
    if [ $opt -eq 1 ]; then
	sudo apt-get install elasticsearch
    elif [ $opt -eq 2 ]; then
	sudo yum install elasticsearch
    else
	echo "Wrong choice! Program Terminated!"
	echo "Error: Unable to continue for this very reason!"
	exit
    fi
}

run_django(){
    # go to src
    cd scholarec_web/
    # add permission: executable to server script
    chmod +x manage.py
    # start server on default port 8000
    # to change port, specify port as argument
    ./manage.py syncdb
    ./manage.py runserver 
}

install
run_django
